### ISSUE TITLE
Test cases failed locally

### ISSUE THREAD

**Issue by oovm** [bokuweb/docx-rs#388]
## Describe the bug

I found that my docx file could not be read, and then after I cloned the repo, the test case did not pass locally.

## Reproduced step

```sh
git clone https://github.com/bokuweb/docx-rs.git
cd docx-rs
cargo test -- --test-threads=1
```

## Expected behavior

All pass.

## Actual behavior

```rs
running 38 tests
failures:

---- reader::read_bom stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:148:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- reader::read_bookmark stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:163:32

---- reader::read_comment stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:238:32

---- reader::read_decoration stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:42:32

---- reader::read_extended_comment stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:253:32

---- reader::read_from_doc stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:208:32

---- reader::read_hello stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:12:32

---- reader::read_highlight_and_underline stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:58:32

---- reader::read_history stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:73:32

---- reader::read_indent_word_online stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:88:32

---- reader::read_insert_table stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:178:32

---- reader::read_line_spacing stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:268:32

---- reader::read_lvl_override stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:223:32

---- reader::read_numbering stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:27:32

---- reader::read_tab_and_break stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:103:32

---- reader::read_table_docx stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:118:32

---- reader::read_table_merged_libre_office stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:133:32

---- reader::read_textbox stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ZipError(FileNotFound)', docx-core\tests\reader.rs:193:32


failures:
    reader::read_bom
    reader::read_bookmark
    reader::read_comment
    reader::read_decoration
    reader::read_extended_comment
    reader::read_from_doc
    reader::read_hello
    reader::read_highlight_and_underline
    reader::read_history
    reader::read_indent_word_online
    reader::read_insert_table
    reader::read_line_spacing
    reader::read_lvl_override
    reader::read_numbering
    reader::read_tab_and_break
    reader::read_table_docx
    reader::read_table_merged_libre_office
    reader::read_textbox

test result: FAILED. 20 passed; 18 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s

error: test failed, to rerun pass '-p docx-rs --test lib'
```

## Screenshots

![FAILED. 20 passed; 18 failed](https://user-images.githubusercontent.com/17541209/146725495-2ae2551b-caf9-4d38-bed2-86ca060f4fe4.png)

## Desktop (please complete the following information)

- OS: Window10 20H2

**Comment by oovm** [comment]
All my docs failed to read by `docx_rs::reader::read_docx` because of `ZipError(FileNotFound)`.
